### ISSUE TITLE
[Question] Any way to enable more cores?

### ISSUE THREAD

**Issue by FearlessSpiff** [yurikoles-aur/linux-drm-tip-git#3]
I seem to be too stupid. Tried to alias make to be make -j3 but doesn't seem to make a difference. Thanks.

**Comment by yurikoles** [comment]
https://wiki.archlinux.org/title/makepkg#Parallel_compilation

**Comment by FearlessSpiff** [comment]
> https://wiki.archlinux.org/title/makepkg#Parallel_compilation

Thanks!
